spring:
  application:
    name: springdatajpa
  datasource:
    url: jdbc:mysql://localhost:3306/springdata_jpa?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: admin
jpa:
  database: MySQL
  show-sql: true
  hibernate:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
server:
  port: 8081